# Generated by Django 4.0 on 2022-02-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chanel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('chanel_url', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
